### PR TITLE
Small portability fix and a typo.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by cbrueffer** [comment]
Even better would be just using #!/bin/sh, since I don't think any bash-specific features are being used here.

**Comment by gpertea** [comment]
Thank you, typo fixed. 
About replacing /bin/bash ... I don't know, seems a bit silly to call a basic shell interpreter through env just because of one relatively rare OS exception -- sorry for the apparent lack of FreeBSD love but pretty much every other platform has /bin/bash (even that fancy FreeBSD window dresser called OS X).

**Comment by cbrueffer** [comment]
True; on the other hand, the change is inconsequential on Linux, but makes the software work out of the box on several other OS :-)

Do any of the scripts even use bash specific features? If not, using #!/bin/sh would be an even better option that's guaranteed to work on any Unix.

**Comment by gpertea** [comment]
OK, as I had to mess up with the tophat2 script again anyway, I'll just follow your suggestion of using env to find bash, it is indeed more portable this way.

**Pull request closed without merging**
