### PR TITLE
update included SeqAn version to 1.4.2

### LINKED ISSUE #7: error while building tophat
http://fpaste.org/227972/32373631/

### PR DESCRIPTION
**Pull request by wookietreiber**
- makes TopHat, to be more specific the included SeqAn version, compile with up to date gcc (tested with gcc 5.2.0)
- patch taken from http://http.debian.net/debian/pool/main/t/tophat/tophat_2.1.0+dfsg-1.debian.tar.xz
- fixes #7
- the PR appears extensive because of the complete replacement of SeqAn 1.3 with SeqAn 1.4, the actual changes are minimal

### CODE REVIEW

**Comment by wookietreiber** [comment]
Is there any feedback on this PR?

**Comment by wookietreiber** [comment]
Is someone still maintaining this project?

**Comment by ctrapnell** [comment]
Yes though the maintainers spend most of their time on HISAT and other projects.

**Comment by blaiseli** [comment]
@wookietreiber I used your "update-seqan" branch, and it allowed me to compile tophat on a debian computing server where I'm not root.

I support this pull request.

**Comment by gpertea** [comment]
There is actually a problem with this patch as some SeqAn DNAString conversion code in segment_juncs.cpp  does not work correctly with it (though it does compile OK), causing some subtle problems at that stage (missing junctions or sometimes many incorrectly reported junctions causing much longer running times etc.). I fixed should be included in the 2.1.1 maintenance release.

**Pull request closed without merging**
